enhancement

diff --git a/.github/workflows/acc-prd-deployments.yml b/.github/workflows/acc-prd-deployments.yml
--- a/.github/workflows/acc-prd-deployments.yml
+++ b/.github/workflows/acc-prd-deployments.yml
@@ -6,10 +6,6 @@ on:
       deployment-module:
         required: false
         type: string
-      time-zone:
-        required: false
-        default: "Europe/Amsterdam"
-        type: string
       timeout-minutes:
         required: false
         default: 10
@@ -17,15 +13,11 @@ on:
 
 
 jobs:
-  maven-release:
-    # Only run if the commit message does not contain '[maven-release-plugin]',  commit is made by mvn.
-    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
+  maven-release-acc-prd-deployment:
     runs-on: ubuntu-24.04
     timeout-minutes: ${{ inputs.timeout-minutes }}
     env:
-      TZ: ${{ inputs.time-zone }}
       GH_TOKEN: ${{ secrets.GH_PAT }}
-      MAVEN_ARGS: '-B -U -V -fae --no-transfer-progress'
     steps:
       - name: Checkout code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -55,7 +47,8 @@ jobs:
 
       - name: Set up Git credentials
         run: |
-          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
+          git config --global user.name "github-actions"
+          git config --global user.email "github-actions@github.com"
           git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}".insteadOf "git@github.com:${{ github.repository }}.git"
           git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
           git fetch --tags --prune
@@ -73,18 +66,13 @@ jobs:
 
       - name: Maven Release Prepare
         run: |
-          mvn -B -U release:prepare -fae || { echo "Maven Release Prepare failed."; exit 1; }
+          mvn release:prepare -B -U -V -fae -ntp || { echo "Maven Release Prepare failed."; exit 1; }
 
       - name: Maven Release Perform
         id: release-output
         run: |
           trap 'echo "Error occurred. Rolling back..."; mvn -B release:rollback' ERR
-          mvn -B -U release:perform -fae
-
-      - name: Create and Auto-Merge Pull Request
-        run: |
-          PROJECT_VERSION=$(git describe --tags --abbrev=0 | sed 's/^[^0-9]*//')
-          gh pr create --base ${{ github.event.repository.default_branch }} --head ${{ steps.name-release-branch.outputs.branch }} --title "Release of version $PROJECT_VERSION" --body "This PR merges the Maven release changes."
+          mvn release:perform -B -U -V -fae -ntp
 
       - name: ECR Login
         if: ${{ inputs.deployment-module }}
@@ -93,7 +81,7 @@ jobs:
       - name: Prepare Docker image tag and repository
         if: ${{ inputs.deployment-module }}
         run: |
-          FILE=$(find ${{ inputs.deployment-module }}/target -maxdepth 1 -type f \( -name "*.war" -o -name "*.jar" \))
+          FILE=$(find ./target/checkout/${{ inputs.deployment-module }}/target -maxdepth 1 -type f \( -name "*.war" -o -name "*.jar" \))
           IMAGE_TAG=$(basename $FILE | sed 's/\.\(jar\|war\)$//')-$(echo ${{ github.sha }} | cut -c1-7)
           ECR_REPO=917951871879.dkr.ecr.eu-west-1.amazonaws.com/${{ github.event.repository.name }}
           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
@@ -102,17 +90,25 @@ jobs:
       - name: Build, push Docker images.
         if: ${{ inputs.deployment-module }}
         run: |
-          docker build -t ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}  ${{ inputs.deployment-module }}
-          docker push ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} 
+          docker build -t ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}  ./target/checkout/${{ inputs.deployment-module }}
+          docker push ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
 
       - name: Update image in Kubernetes deployment
         if: ${{ inputs.deployment-module }}
         run: |
-          # Update the Kubernetes deployment files with the new image tag
-          sed -i "s|newTag: .*|newTag: ${{ env.IMAGE_TAG }}|" "/k8s/acc/kustomization.yml"
-          sed -i "s|newTag: .*|newTag: ${{ env.IMAGE_TAG }}|" "/k8s/prd/kustomization.yml"
-          git add /k8s/acc/kustomization.yml /k8s/prd/kustomization.yml
-          git commit -m "Update image tag to ${{ env.IMAGE_TAG }} in acc and prd deployments"
-          git push
+          git fetch && git pull origin ${{ steps.name-release-branch.outputs.branch }}
+          sed -i "s|newTag: .*|newTag: ${{ env.IMAGE_TAG }}|" ./k8s/acc/kustomization.yml
+          sed -i "s|newTag: .*|newTag: ${{ env.IMAGE_TAG }}|" ./k8s/prd/kustomization.yml
+          git add ./k8s/acc/kustomization.yml ./k8s/prd/kustomization.yml
+          git commit -m "[acc & prd deployments] Update image ${{ env.IMAGE_TAG }} in acc and prd deployments" 
+          git push origin ${{ steps.name-release-branch.outputs.branch }}
+          
+          PROJECT_VERSION=$(git describe --tags --abbrev=0 | sed 's/^[^0-9]*//')
+          gh pr create \
+            --title "Release of version $PROJECT_VERSION" \
+            --body "This PR merges the Maven release changes and update image in acc & prd deployments." \
+            --head ${{ steps.name-release-branch.outputs.branch }} \
+            --base ${{ github.event.repository.default_branch }}
+          
           gh pr merge ${{ github.head_ref }} --merge --admin
       
diff --git a/.github/workflows/tst-deployment.yml b/.github/workflows/tst-deployment.yml
--- a/.github/workflows/tst-deployment.yml
+++ b/.github/workflows/tst-deployment.yml
@@ -3,10 +3,6 @@ name: Test(tst) env Deployment
 on:
   workflow_call:
     inputs:
-      time-zone:
-        required: false
-        default: "Europe/Amsterdam"
-        type: string
       deployment-module:
         required: false
         type: string
@@ -16,13 +12,11 @@ on:
         type: number
 
 jobs:
-  maven-deploy:
+  maven-deploy-tst-deployment:
     runs-on: ubuntu-24.04
     timeout-minutes: ${{ inputs.timeout-minutes }}
     env:
-      TZ: ${{ inputs.time-zone }}
       GH_TOKEN: ${{ secrets.GH_PAT }}
-      MAVEN_ARGS: '-B -U -V -fae -DskipTests --no-transfer-progress'
 
     steps:
       - name: Checkout code
@@ -53,7 +47,7 @@ jobs:
 
       - name: Maven Deploy
         run: |
-          mvn clean deploy || { echo "Maven Deploy failed."; exit 1; }
+          mvn clean deploy -B -U -V -fae -ntp -DskipTests || exit 1 || { echo "Maven Deploy failed."; exit 1; }
 
       - name: ECR Login
         if: ${{ inputs.deployment-module }}
@@ -69,34 +63,33 @@ jobs:
           echo "ECR_REPO=$ECR_REPO" >> $GITHUB_ENV
 
       - name: Build, push Docker images.
-
-        run: |
-          docker build -t ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}  ${{ inputs.deployment-module }}
-          docker push ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} 
-
-      - name: Create and Push Release Branch
-        run: |
-          git checkout -b update-tst-deployment-image || git checkout update-tst-deployment-image
-          git push origin update-tst-deployment-image -f
-
-      - name: Update image in Kubernetes deployment
         if: ${{ inputs.deployment-module }}
         run: |
-          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
-          git checkout -b update-tst-deployment-image || git checkout update-tst-deployment-image
-          sed -i "s|newTag: .*|newTag: ${{ image_tag }}|" "/k8s/tst/kustomization.yml"
-          git add /k8s/tst/kustomization.yml
-          git commit -m "Update image tag to $IMAGE_TAG in project "/k8s/tst/kustomization.yml" -a
-          git push origin update-tst-deployment-image -f
+          docker build -t ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}  ${{ inputs.deployment-module }}
+          docker push ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
 
-      - name: Create and Auto-Merge Pull Request
+      - name: Update image and auto-merge PR
+        if: ${{ inputs.deployment-module }}
         run: |
-          gh pr create --title "Update image tag to ${{ env.IMAGE_TAG }}" \
-                      --body "This PR updates the image tag in the Kubernetes deployment files." \
-                      --head ${{ github.head_ref }} \
-                      --base ${{ github.event.repository.default_branch }}
-          gh pr merge ${{ github.head_ref }} --merge --admin
-          
+          git config --global user.name "github-actions"
+          git config --global user.email "github-actions@github.com"
+
+          branch=update-tst-deployment-image
+          deployment_path=./k8s/tst/kustomization.yml
+          git checkout -b $branch || git checkout $branch
+
+          sed -i "s|newTag: .*|newTag: ${{ env.IMAGE_TAG }}|" $deployment_path
+          git add $deployment_path
+          git commit -m "[gh-workflow] Update image to ${{ env.IMAGE_TAG }} in $deployment_path" || exit 0
+          git push origin $branch -f
+
+          gh pr create \
+            --title "Update image tag to ${{ env.IMAGE_TAG }}" \
+            --body "Updates image tag in Kubernetes deployment." \
+            --head $branch \
+            --base ${{ github.event.repository.default_branch }}
+
+          gh pr merge $branch --merge --admin
           
           
                     
