Remove -ntp option from Maven deploy command

diff --git a/.github/workflows/maven-deploy.yml b/.github/workflows/maven-deploy.yml
--- a/.github/workflows/maven-deploy.yml
+++ b/.github/workflows/maven-deploy.yml
@@ -48,7 +48,7 @@ jobs:
 
       - name: Maven Deploy
         run: |
-          mvn clean deploy -B -U -V -fae -ntp -DskipTests|| { echo "Maven Deploy failed."; exit 1; }
+          mvn clean deploy -B -U -V -fae  -DskipTests|| { echo "Maven Deploy failed."; exit 1; }
 
       - name: Find all folders with Dockerfile
         run: |
