remove the pipefail when it is not needed

diff --git a/.github/workflows/maven-deploy.yml b/.github/workflows/maven-deploy.yml
--- a/.github/workflows/maven-deploy.yml
+++ b/.github/workflows/maven-deploy.yml
@@ -31,8 +31,7 @@ jobs:
 
       - name: Maven Deploy
         run: |
-          set -o pipefail
-          mvn clean deploy --batch-mode -fae
+          mvn clean deploy --batch-mode -fae || { echo "Maven Deploy failed."; exit 1; }
 
       - name: Find all folders with Dockerfile
         run: |
