improvements

diff --git a/.github/workflows/publish-image.yml b/.github/workflows/publish-image.yml
--- a/.github/workflows/publish-image.yml
+++ b/.github/workflows/publish-image.yml
@@ -5,25 +5,25 @@ name: Build and Push Docker Image
 on:
   workflow_call:
     inputs:
-      runner-label:
-        required: true
-        type: string
       artifact-url:
         description: 'The URL of the Artifact WAR file to be downloaded'
         required: true
         type: string
+      runner-label:
+        required: false
+        default: 'ubuntu-24.04'
+        type: string
+      maven-repo:
+        required: false
+        default: 'code-artifact'
+        type: string
 
 jobs:
-  build-push-image:
-    runs-on: ${{inputs.runner-label}}
+  publish-image:
+    runs-on: ${{ inputs.runner-label }}
     steps:
-      - name: Get Metadata as env variables
-        run: |
-          echo "IMAGE_TAG=$(basename ${{ inputs.artifact-url }} | sed 's/\.[^.]*$//')-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
-
-      - name: Download Artifact WAR
-        run: |
-          curl -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" -f -o "ROOT.war" "${{ inputs.artifact-url }}"
+      - name: Checkout code
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
       - name: AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -31,22 +31,36 @@ jobs:
           aws-region: eu-west-1
           role-to-assume: arn:aws:iam::917951871879:role/GitHubActionsBgOrg
 
+      - name: Get CodeArtifact Authorization Token
+        if: ${{ inputs.maven-repo == 'code-artifact' }}
+        run: |
+          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact  get-authorization-token --domain nisv-ateam --domain-owner 917951871879 --region eu-west-1 --query authorizationToken --output text)
+          echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"
+          echo "CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> "$GITHUB_ENV"
+
+      - name: Get Metadata as env variables
+        run: |
+          echo "IMAGE_TAG=$(basename ${{ inputs.artifact-url }} | sed 's/\.[^.]*$//')-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
+
+      - name: Download Artifact WAR
+        run: |
+          if [[ "${{ inputs.maven-repo }}" == 'code-artifact' ]]; then
+            curl -H "Authorization: Bearer ${{ env.CODEARTIFACT_AUTH_TOKEN }}" -f -L "${{ inputs.artifact-url }}" -o "ROOT.war" || { echo "Failed to download artifact."; exit 1; }
+          elif [[ "${{ inputs.maven-repo }}" == 'beng-nexus' ]]; then
+            curl -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" -f "${{ inputs.artifact-url }}" -o "ROOT.war" || { echo "Failed to download artifact."; exit 1; }
+          else
+            echo "Invalid Maven repository: ${{ inputs.maven-repo }}" && exit 1
+          fi
+
       - name: ECR Login
-        uses: aws-actions/amazon-ecr-login@v2
+        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 #v2.0.1
 
       - name: Build image
         run: |
-          docker build -t 917951871879.dkr.ecr.eu-west-1.amazonaws.com/museum-api:${{ env.IMAGE_TAG }} \
-          --build-arg BASE_IMAGE=${{ vars.BASE_IMAGE }} \
-          --build-arg WAR_FILE_PATH="ROOT.war" .
+          docker build -t 917951871879.dkr.ecr.eu-west-1.amazonaws.com/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }} --build-arg WAR_FILE_PATH="ROOT.war"  .
 
       - name: Push Image to AWS ECR Repository
         run: |
-          docker push "917951871879.dkr.ecr.eu-west-1.amazonaws.com/museum-api:${{ env.IMAGE_TAG }}"
-
-      - name: Post Maven Clean
-        run: mvn clean
-
-      - name: Post Clean Docker Images
-        run: |
-          docker rmi 917951871879.dkr.ecr.eu-west-1.amazonaws.com/museum-api:${{ env.IMAGE_TAG }}
+          docker push "917951871879.dkr.ecr.eu-west-1.amazonaws.com/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }}"
+          
+      
